# Generated by Django 3.2.25 on 2024-10-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userapp", "0005_intrauser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="userAvatar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("avatar", models.CharField(max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
