# Generated by Django 3.2.25 on 2024-10-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20241021_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='intra_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.intrauser'),
        ),
    ]
