# Generated by Django 3.2.25 on 2024-10-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0009_alter_useravatar_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfriend",
            name="intra_friend",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intra_friend",
                to="userapp.intrauser",
            ),
        ),
        migrations.AddField(
            model_name="userfriend",
            name="intra_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intra_user",
                to="userapp.intrauser",
            ),
        ),
    ]
