# Generated by Django 3.2.25 on 2024-10-21 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0010_auto_20241021_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_intra_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfriend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_intra_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
