# Generated by Django 3.2.25 on 2024-10-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_lastactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastactive',
            name='intrauser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.intrauser'),
        ),
    ]
