# Generated by Django 3.2.25 on 2024-12-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentsWon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=40)),
                ('won', models.IntegerField(default=0)),
            ],
        ),
    ]
