# Generated by Django 3.2.25 on 2024-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_tournamentswon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tournamentswon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
