

services:
  postgres:
    container_name: postgres
    build:
      context: ./requirements/postgres/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - nwtranscendence
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: backend
    build:
      context: ./requirements/backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - nwtranscendence
    volumes:
      - backend-volume:/app
    depends_on:
      - postgres
    restart: always

  backendmicro:
    container_name: backendmicro
    build:
      context: ./requirements/backendmicro/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8002"
    networks:
      - nwtranscendence
    volumes:
      - backendmicro-volume:/app
    depends_on:
      - postgres
    restart: always

  frontend:
      container_name: frontend
      build:
        context: ./requirements/frontend/
        dockerfile: Dockerfile
        args:
          CERTIFICATE_PATH: ${CERTIFICATE_PATH}
          VALUE: ${VALUE}
      env_file:
        - .env
      ports:
        - "443:443"
      networks:
        - nwtranscendence
      depends_on:
        - backend
      volumes:
        - frontend-volume:/var/www/html
      restart: always 

volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/vatche/Documents/dbforft

  backend-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/vatche/Desktop/TRAN/ft_transcendence/backend/backend

  
  backendmicro-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/vatche/Desktop/TRAN/ft_transcendence/backendmicro/backendmicro

  frontend-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/vatche/Desktop/TRAN/ft_transcendence/frontend/html


networks:
    nwtranscendence:
        driver: bridge