

services:
  postgres:
    container_name: postgres
    build:
      context: ./requirements/postgres/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - nwtranscendence
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always

  django:
    container_name: django
    build:
      context: ./requirements/django/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - nwtranscendence
    volumes:
      - django-volume:/app
    depends_on:
      - postgres
    restart: always

  frontend:
      container_name: frontend
      build:
        context: ./requirements/frontend/
        dockerfile: Dockerfile
        args:
          CERTIFICATE_PATH: ${CERTIFICATE_PATH}
          VALUE: ${VALUE}
      env_file:
        - .env
      ports:
        - "443:443"
      networks:
        - nwtranscendence
      depends_on:
        - django
      volumes:
        - frontend-volume:/var/www
      restart: always 

volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/vatche/Documents/dbforft

  django-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/vatche/Desktop/ft_transcendence/backend/userapp

  frontend-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/vatche/Desktop/ft_transcendence/frontend/www/html



networks:
    nwtranscendence:
        driver: bridge